# Generated by Django 6.1 on 2026-09-16 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=25)),
                ('idade', models.IntegerField(max_length=3)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=25)),
                ('idade', models.IntegerField(max_length=3)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=15)),
                ('turno', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_escola.aluno')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_escola.professor')),
            ],
        ),
    ]
